version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: web
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/compose-postgres
      - DATABASE_USERNAME=compose-postgres
      - DATABASE_PASSWORD=compose-postgres
      - BARENTS_WATCH_CLIENT_ID=${BARENTS_WATCH_CLIENT_ID}
      - BARENTS_WATCH_CLIENT_SECRET=${BARENTS_WATCH_CLIENT_SECRET}

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  frontend:
    depends_on:
      - app
    container_name: frontend
    build:
      context: navis-app
    volumes:
      - './navis-app:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
